apiVersion: v2
name: hff-app
description: A Helm chart for HFF application deployment
type: application
version: 1.0.2
appVersion: "1.0.0"
keywords:
  - hff
  - application
maintainers:
  - name: Home Office Digital
