{{- if .Values.ingress.externalEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-external
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: hff-app
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- toYaml .Values.ingress.external.annotations | nindent 4 }}
spec:
  ingressClassName: nginx-external
  {{- if eq .Values.global.environment "dev" }}
  tls:
  - hosts:
    - {{ .Values.ingress.external.hosts.dev }}
    secretName: {{ .Values.ingress.external.tls.certName }}
  rules:
  - host: {{ .Values.ingress.external.hosts.dev }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: {{ .Values.service.ports.https }}
  {{- end }}
{{- end }}
