{{- if .Values.certificates.enabled }}
{{- if .Values.certificates.branch.internal.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.internal.tls.branchCertName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: hff-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    cert-manager.io/solver: route53
spec:
  commonName: {{ .Values.certificates.branch.internal.commonName }}
  dnsNames:
    - {{ .Values.certificates.branch.internal.commonName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificates.branch.internal.issuer }}
  secretName: {{ .Values.ingress.internal.tls.branchCertName }}
{{- end }}
{{- end }}
