name: Lint and validate Helm chart

on:
    pull_request:
        branches:
            - master
            - CCL-*
    push:
        branches:
            - CCL-*
            - master

jobs:
  validation:
    uses: Home-Office-Digital/core-cloud-workflow-helm-ecr-actions/.github/workflows/validation.yml@1.0.0
    with:
      chart_directory: "charts"
      helm_version: ""
      run_unittest: true
