name: Building and scanning Yarn Package

on:
    push:
        branches:
            - CCL-8890
jobs:
    validation:
        uses: Home-Office-Digital/core-cloud-workflow-node-yarn-actions/.github/workflows/validation.yml@1.3.1
        with:
            working_directory: "."
            node_version: "20"
            audit_level: "low"
            post_install_script: ""

    build-publish:
        uses: Home-Office-Digital/core-cloud-workflow-node-yarn-actions/.github/workflows/build-publish.yml@1.3.1
        with:
            working_directory: "."
            node_version: "20"
            should_publish: false
            registry_url: ""
        secrets:
            node_access_token: ${{ secrets.NODE_ACCESS_TOKEN }}